name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y build-essential pkg-config libssl-dev clang cmake llvm g++-aarch64-linux-gnu gcc-aarch64-linux-gnu

      - name: Install protoc
        id: deps-protoc
        shell: bash
        run: |
          curl -Lo /tmp/protoc.zip \
          "https://github.com/protocolbuffers/protobuf/releases/download/v27.3/protoc-27.3-linux-x86_64.zip"
          unzip -o /tmp/protoc.zip -d ${HOME}/.local
          echo "PROTOC=${HOME}/.local/bin/protoc" >> $GITHUB_ENV
          export PATH="${PATH}:${HOME}/.local/bin"

      - name: Add Rust targets
        run: rustup target add x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu

      - name: Build for Linux x86
        run: cargo build -r --target=x86_64-unknown-linux-gnu --verbose && mv target/x86_64-unknown-linux-gnu/release/platform-cli ./platform-cli-gnu-x86_64

      - name: Build for Linux arm64
        run: cargo build -r --target=aarch64-unknown-linux-gnu --verbose && mv target/unknown-linux-gnu/release/platform-cli ./platform-cli-gnu-arm64

  build_max_x86_64:
    name: Build Apple (x86_64)
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Add Rust targets
        run: brew install llvm protobuf

      - name: Add Rust targets
        run: rustup target add x86_64-apple-darwin

      - name: Build for Apple x86
        run: cargo build -r --target=x86_64-apple-darwin --verbose && mv target/x86_64-apple-darwin/release/platform-cli ./platform-cli_darwin-x86_64

  build_max_arm64:
    name: Build Apple (arm64)
    runs-on: macos-15
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Add Rust targets
        run: brew install llvm protobuf

      - name: Add Rust targets
        run: rustup target add aarch64-apple-darwin

      - name: Build for Apple Silicon
        run: cargo build -r --target=aarch64-apple-darwin --verbose && mv target/aarch64-apple-darwin/release/platform-cli ./platform-cli_darwin-arm64

