name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose
