name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Install protoc
        id: deps-protoc
        shell: bash
        run: |
          curl -Lo /tmp/protoc.zip \
          "https://github.com/protocolbuffers/protobuf/releases/download/v27.3/protoc-27.3-linux-x86_64.zip"
          unzip -o /tmp/protoc.zip -d ${HOME}/.local
          echo "PROTOC=${HOME}/.local/bin/protoc" >> $GITHUB_ENV
          export PATH="${PATH}:${HOME}/.local/bin"

      - name: Build
        run: cargo build --verbose
